/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.1.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Availability model module.
 * @module model/Availability
 * @version 0.1.0
 */
class Availability {
    /**
     * Constructs a new <code>Availability</code>.
     * @alias module:model/Availability
     */
    constructor() { 
        
        Availability.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Availability</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Availability} obj Optional instance to populate.
     * @return {module:model/Availability} The populated <code>Availability</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Availability();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('availability')) {
                obj['availability'] = ApiClient.convertToType(data['availability'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('last_checked_at')) {
                obj['last_checked_at'] = ApiClient.convertToType(data['last_checked_at'], 'Date');
            }
            if (data.hasOwnProperty('last_valid_at')) {
                obj['last_valid_at'] = ApiClient.convertToType(data['last_valid_at'], 'Date');
            }
            if (data.hasOwnProperty('resource_id')) {
                obj['resource_id'] = ApiClient.convertToType(data['resource_id'], 'String');
            }
            if (data.hasOwnProperty('resource_type')) {
                obj['resource_type'] = ApiClient.convertToType(data['resource_type'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} action
 */
Availability.prototype['action'] = undefined;

/**
 * @member {String} availability
 */
Availability.prototype['availability'] = undefined;

/**
 * @member {Date} created_at
 */
Availability.prototype['created_at'] = undefined;

/**
 * ID of the resource
 * @member {String} id
 */
Availability.prototype['id'] = undefined;

/**
 * @member {String} identifier
 */
Availability.prototype['identifier'] = undefined;

/**
 * @member {Date} last_checked_at
 */
Availability.prototype['last_checked_at'] = undefined;

/**
 * @member {Date} last_valid_at
 */
Availability.prototype['last_valid_at'] = undefined;

/**
 * ID of the resource
 * @member {String} resource_id
 */
Availability.prototype['resource_id'] = undefined;

/**
 * @member {String} resource_type
 */
Availability.prototype['resource_type'] = undefined;

/**
 * @member {Date} updated_at
 */
Availability.prototype['updated_at'] = undefined;






export default Availability;

