/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.1.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Tagging from './Tagging';

/**
 * The ContainerNode model module.
 * @module model/ContainerNode
 * @version 0.1.0
 */
class ContainerNode {
    /**
     * Constructs a new <code>ContainerNode</code>.
     * @alias module:model/ContainerNode
     */
    constructor() { 
        
        ContainerNode.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContainerNode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContainerNode} obj Optional instance to populate.
     * @return {module:model/ContainerNode} The populated <code>ContainerNode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerNode();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('cpus')) {
                obj['cpus'] = ApiClient.convertToType(data['cpus'], 'Number');
            }
            if (data.hasOwnProperty('lives_on_type')) {
                obj['lives_on_type'] = ApiClient.convertToType(data['lives_on_type'], 'String');
            }
            if (data.hasOwnProperty('lives_on_id')) {
                obj['lives_on_id'] = ApiClient.convertToType(data['lives_on_id'], Object);
            }
            if (data.hasOwnProperty('memory')) {
                obj['memory'] = ApiClient.convertToType(data['memory'], 'Number');
            }
            if (data.hasOwnProperty('source_created_at')) {
                obj['source_created_at'] = ApiClient.convertToType(data['source_created_at'], 'Date');
            }
            if (data.hasOwnProperty('source_deleted_at')) {
                obj['source_deleted_at'] = ApiClient.convertToType(data['source_deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
            if (data.hasOwnProperty('taggings')) {
                obj['taggings'] = ApiClient.convertToType(data['taggings'], [Tagging]);
            }
            if (data.hasOwnProperty('archived_at')) {
                obj['archived_at'] = ApiClient.convertToType(data['archived_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ContainerNode.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ContainerNode.prototype['name'] = undefined;

/**
 * @member {Number} cpus
 */
ContainerNode.prototype['cpus'] = undefined;

/**
 * @member {String} lives_on_type
 */
ContainerNode.prototype['lives_on_type'] = undefined;

/**
 * @member {Object} lives_on_id
 */
ContainerNode.prototype['lives_on_id'] = undefined;

/**
 * @member {Number} memory
 */
ContainerNode.prototype['memory'] = undefined;

/**
 * @member {Date} source_created_at
 */
ContainerNode.prototype['source_created_at'] = undefined;

/**
 * @member {Date} source_deleted_at
 */
ContainerNode.prototype['source_deleted_at'] = undefined;

/**
 * @member {String} source_id
 */
ContainerNode.prototype['source_id'] = undefined;

/**
 * @member {String} source_ref
 */
ContainerNode.prototype['source_ref'] = undefined;

/**
 * @member {String} tenant_id
 */
ContainerNode.prototype['tenant_id'] = undefined;

/**
 * @member {Array.<module:model/Tagging>} taggings
 */
ContainerNode.prototype['taggings'] = undefined;

/**
 * @member {Date} archived_at
 */
ContainerNode.prototype['archived_at'] = undefined;






export default ContainerNode;

