/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.1.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Container model module.
 * @module model/Container
 * @version 0.1.0
 */
class Container {
    /**
     * Constructs a new <code>Container</code>.
     * @alias module:model/Container
     */
    constructor() { 
        
        Container.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Container</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Container} obj Optional instance to populate.
     * @return {module:model/Container} The populated <code>Container</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Container();

            if (data.hasOwnProperty('archived_at')) {
                obj['archived_at'] = ApiClient.convertToType(data['archived_at'], 'Date');
            }
            if (data.hasOwnProperty('container_group_id')) {
                obj['container_group_id'] = ApiClient.convertToType(data['container_group_id'], 'String');
            }
            if (data.hasOwnProperty('container_image_id')) {
                obj['container_image_id'] = ApiClient.convertToType(data['container_image_id'], 'String');
            }
            if (data.hasOwnProperty('cpu_limit')) {
                obj['cpu_limit'] = ApiClient.convertToType(data['cpu_limit'], 'Number');
            }
            if (data.hasOwnProperty('cpu_request')) {
                obj['cpu_request'] = ApiClient.convertToType(data['cpu_request'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('memory_limit')) {
                obj['memory_limit'] = ApiClient.convertToType(data['memory_limit'], 'Number');
            }
            if (data.hasOwnProperty('memory_request')) {
                obj['memory_request'] = ApiClient.convertToType(data['memory_request'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} archived_at
 */
Container.prototype['archived_at'] = undefined;

/**
<<<<<<< HEAD
 * ID of the resource
=======
>>>>>>> Update API definition, use v0.1 and resolve ID/IDReadonly problem.
 * @member {String} container_group_id
 */
Container.prototype['container_group_id'] = undefined;

/**
<<<<<<< HEAD
 * ID of the resource
=======
>>>>>>> Update API definition, use v0.1 and resolve ID/IDReadonly problem.
 * @member {String} container_image_id
 */
Container.prototype['container_image_id'] = undefined;

/**
 * @member {Number} cpu_limit
 */
Container.prototype['cpu_limit'] = undefined;

/**
 * @member {Number} cpu_request
 */
Container.prototype['cpu_request'] = undefined;

/**
 * @member {Date} created_at
 */
Container.prototype['created_at'] = undefined;

/**
<<<<<<< HEAD
 * ID of the resource
=======
>>>>>>> Update API definition, use v0.1 and resolve ID/IDReadonly problem.
 * @member {String} id
 */
Container.prototype['id'] = undefined;

/**
 * @member {Number} memory_limit
 */
Container.prototype['memory_limit'] = undefined;

/**
 * @member {Number} memory_request
 */
Container.prototype['memory_request'] = undefined;

/**
 * @member {String} name
 */
Container.prototype['name'] = undefined;

/**
 * @member {Date} updated_at
 */
Container.prototype['updated_at'] = undefined;






export default Container;

