/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.1.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Tagging from './Tagging';

/**
 * The ContainerProject model module.
 * @module model/ContainerProject
 * @version 0.1.0
 */
class ContainerProject {
    /**
     * Constructs a new <code>ContainerProject</code>.
     * @alias module:model/ContainerProject
     */
    constructor() { 
        
        ContainerProject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContainerProject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContainerProject} obj Optional instance to populate.
     * @return {module:model/ContainerProject} The populated <code>ContainerProject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerProject();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
            if (data.hasOwnProperty('taggings')) {
                obj['taggings'] = ApiClient.convertToType(data['taggings'], [Tagging]);
            }
            if (data.hasOwnProperty('archived_at')) {
                obj['archived_at'] = ApiClient.convertToType(data['archived_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ContainerProject.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ContainerProject.prototype['name'] = undefined;

/**
 * @member {String} display_name
 */
ContainerProject.prototype['display_name'] = undefined;

/**
 * @member {String} source_id
 */
ContainerProject.prototype['source_id'] = undefined;

/**
 * @member {String} source_ref
 */
ContainerProject.prototype['source_ref'] = undefined;

/**
 * @member {String} tenant_id
 */
ContainerProject.prototype['tenant_id'] = undefined;

/**
 * @member {Array.<module:model/Tagging>} taggings
 */
ContainerProject.prototype['taggings'] = undefined;

/**
 * @member {Date} archived_at
 */
ContainerProject.prototype['archived_at'] = undefined;






export default ContainerProject;

