/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.1.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrchestrationStack model module.
 * @module model/OrchestrationStack
 * @version 0.1.0
 */
class OrchestrationStack {
    /**
     * Constructs a new <code>OrchestrationStack</code>.
     * @alias module:model/OrchestrationStack
     */
    constructor() { 
        
        OrchestrationStack.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrchestrationStack</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrchestrationStack} obj Optional instance to populate.
     * @return {module:model/OrchestrationStack} The populated <code>OrchestrationStack</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrchestrationStack();

            if (data.hasOwnProperty('archived_at')) {
                obj['archived_at'] = ApiClient.convertToType(data['archived_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('last_seen_at')) {
                obj['last_seen_at'] = ApiClient.convertToType(data['last_seen_at'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('source_created_at')) {
                obj['source_created_at'] = ApiClient.convertToType(data['source_created_at'], 'Date');
            }
            if (data.hasOwnProperty('source_deleted_at')) {
                obj['source_deleted_at'] = ApiClient.convertToType(data['source_deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} archived_at
 */
OrchestrationStack.prototype['archived_at'] = undefined;

/**
 * @member {Date} created_at
 */
OrchestrationStack.prototype['created_at'] = undefined;

/**
 * Description of the OrchestrationStack
 * @member {String} description
 */
OrchestrationStack.prototype['description'] = undefined;

/**
<<<<<<< HEAD
 * ID of the resource
=======
>>>>>>> Update API definition, use v0.1 and resolve ID/IDReadonly problem.
 * @member {String} id
 */
OrchestrationStack.prototype['id'] = undefined;

/**
 * @member {Date} last_seen_at
 */
OrchestrationStack.prototype['last_seen_at'] = undefined;

/**
 * @member {String} name
 */
OrchestrationStack.prototype['name'] = undefined;

/**
 * @member {Date} source_created_at
 */
OrchestrationStack.prototype['source_created_at'] = undefined;

/**
 * @member {Date} source_deleted_at
 */
OrchestrationStack.prototype['source_deleted_at'] = undefined;

/**
 * ID of the resource
 * @member {String} source_id
 */
OrchestrationStack.prototype['source_id'] = undefined;

/**
 * @member {String} source_ref
 */
OrchestrationStack.prototype['source_ref'] = undefined;

/**
 * @member {Date} updated_at
 */
OrchestrationStack.prototype['updated_at'] = undefined;






export default OrchestrationStack;

