/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.1.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServiceInstance model module.
 * @module model/ServiceInstance
 * @version 0.1.0
 */
class ServiceInstance {
    /**
     * Constructs a new <code>ServiceInstance</code>.
     * @alias module:model/ServiceInstance
     */
    constructor() { 
        
        ServiceInstance.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceInstance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceInstance} obj Optional instance to populate.
     * @return {module:model/ServiceInstance} The populated <code>ServiceInstance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceInstance();

            if (data.hasOwnProperty('archived_at')) {
                obj['archived_at'] = ApiClient.convertToType(data['archived_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('extra')) {
                obj['extra'] = ApiClient.convertToType(data['extra'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('last_seen_at')) {
                obj['last_seen_at'] = ApiClient.convertToType(data['last_seen_at'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('service_offering_id')) {
                obj['service_offering_id'] = ApiClient.convertToType(data['service_offering_id'], 'String');
            }
            if (data.hasOwnProperty('service_plan_id')) {
                obj['service_plan_id'] = ApiClient.convertToType(data['service_plan_id'], 'String');
            }
            if (data.hasOwnProperty('source_created_at')) {
                obj['source_created_at'] = ApiClient.convertToType(data['source_created_at'], 'Date');
            }
            if (data.hasOwnProperty('source_deleted_at')) {
                obj['source_deleted_at'] = ApiClient.convertToType(data['source_deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('source_region_id')) {
                obj['source_region_id'] = ApiClient.convertToType(data['source_region_id'], 'String');
            }
            if (data.hasOwnProperty('subscription_id')) {
                obj['subscription_id'] = ApiClient.convertToType(data['subscription_id'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} archived_at
 */
ServiceInstance.prototype['archived_at'] = undefined;

/**
 * @member {Date} created_at
 */
ServiceInstance.prototype['created_at'] = undefined;

/**
 * Extra information about this object in JSON format
 * @member {String} extra
 */
ServiceInstance.prototype['extra'] = undefined;

/**
 * ID of the resource
 * @member {String} id
 */
ServiceInstance.prototype['id'] = undefined;

/**
 * @member {Date} last_seen_at
 */
ServiceInstance.prototype['last_seen_at'] = undefined;

/**
 * @member {String} name
 */
ServiceInstance.prototype['name'] = undefined;

/**
 * ID of the resource
 * @member {String} service_offering_id
 */
ServiceInstance.prototype['service_offering_id'] = undefined;

/**
 * ID of the resource
 * @member {String} service_plan_id
 */
ServiceInstance.prototype['service_plan_id'] = undefined;

/**
 * @member {Date} source_created_at
 */
ServiceInstance.prototype['source_created_at'] = undefined;

/**
 * @member {Date} source_deleted_at
 */
ServiceInstance.prototype['source_deleted_at'] = undefined;

/**
 * ID of the resource
 * @member {String} source_id
 */
ServiceInstance.prototype['source_id'] = undefined;

/**
 * @member {String} source_ref
 */
ServiceInstance.prototype['source_ref'] = undefined;

/**
 * ID of the resource
 * @member {String} source_region_id
 */
ServiceInstance.prototype['source_region_id'] = undefined;

/**
 * ID of the resource
 * @member {String} subscription_id
 */
ServiceInstance.prototype['subscription_id'] = undefined;

/**
 * @member {Date} updated_at
 */
ServiceInstance.prototype['updated_at'] = undefined;






export default ServiceInstance;

