/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.1.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServiceOfferingIcon model module.
 * @module model/ServiceOfferingIcon
 * @version 0.1.0
 */
class ServiceOfferingIcon {
    /**
     * Constructs a new <code>ServiceOfferingIcon</code>.
     * @alias module:model/ServiceOfferingIcon
     */
    constructor() { 
        
        ServiceOfferingIcon.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceOfferingIcon</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceOfferingIcon} obj Optional instance to populate.
     * @return {module:model/ServiceOfferingIcon} The populated <code>ServiceOfferingIcon</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceOfferingIcon();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ServiceOfferingIcon.prototype['id'] = undefined;

/**
 * @member {String} source_ref
 */
ServiceOfferingIcon.prototype['source_ref'] = undefined;

/**
 * Raw icon data
 * @member {String} data
 */
ServiceOfferingIcon.prototype['data'] = undefined;






export default ServiceOfferingIcon;

