/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.1.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SourceType model module.
 * @module model/SourceType
 * @version 0.1.0
 */
class SourceType {
    /**
     * Constructs a new <code>SourceType</code>.
     * @alias module:model/SourceType
     */
    constructor() { 
        
        SourceType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SourceType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SourceType} obj Optional instance to populate.
     * @return {module:model/SourceType} The populated <code>SourceType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SourceType();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('product_name')) {
                obj['product_name'] = ApiClient.convertToType(data['product_name'], 'String');
            }
            if (data.hasOwnProperty('schema')) {
                obj['schema'] = ApiClient.convertToType(data['schema'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('vendor')) {
                obj['vendor'] = ApiClient.convertToType(data['vendor'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} created_at
 */
SourceType.prototype['created_at'] = undefined;

/**
<<<<<<< HEAD
 * ID of the resource
=======
>>>>>>> Update API definition, use v0.1 and resolve ID/IDReadonly problem.
 * @member {String} id
 */
SourceType.prototype['id'] = undefined;

/**
 * @member {String} name
 */
SourceType.prototype['name'] = undefined;

/**
 * @member {String} product_name
 */
SourceType.prototype['product_name'] = undefined;

/**
 * @member {String} schema
 */
SourceType.prototype['schema'] = undefined;

/**
 * @member {Date} updated_at
 */
SourceType.prototype['updated_at'] = undefined;

/**
 * @member {String} vendor
 */
SourceType.prototype['vendor'] = undefined;






export default SourceType;

