/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.1.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Tagging model module.
 * @module model/Tagging
 * @version 0.1.0
 */
class Tagging {
    /**
     * Constructs a new <code>Tagging</code>.
     * @alias module:model/Tagging
     */
    constructor() { 
        
        Tagging.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Tagging</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tagging} obj Optional instance to populate.
     * @return {module:model/Tagging} The populated <code>Tagging</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tagging();

            if (data.hasOwnProperty('tag_id')) {
                obj['tag_id'] = ApiClient.convertToType(data['tag_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * ID of the resource
 * @member {String} tag_id
 */
Tagging.prototype['tag_id'] = undefined;

/**
 * @member {String} name
 */
Tagging.prototype['name'] = undefined;

/**
 * @member {String} value
 */
Tagging.prototype['value'] = undefined;






export default Tagging;

