/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.1.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Tagging from './Tagging';

/**
 * The Vm model module.
 * @module model/Vm
 * @version 0.1.0
 */
class Vm {
    /**
     * Constructs a new <code>Vm</code>.
     * @alias module:model/Vm
     */
    constructor() { 
        
        Vm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Vm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Vm} obj Optional instance to populate.
     * @return {module:model/Vm} The populated <code>Vm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Vm();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('source_created_at')) {
                obj['source_created_at'] = ApiClient.convertToType(data['source_created_at'], 'Date');
            }
            if (data.hasOwnProperty('source_deleted_at')) {
                obj['source_deleted_at'] = ApiClient.convertToType(data['source_deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
            if (data.hasOwnProperty('uid_ems')) {
                obj['uid_ems'] = ApiClient.convertToType(data['uid_ems'], 'String');
            }
            if (data.hasOwnProperty('hostname')) {
                obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
            }
            if (data.hasOwnProperty('power_state')) {
                obj['power_state'] = ApiClient.convertToType(data['power_state'], 'String');
            }
            if (data.hasOwnProperty('cpus')) {
                obj['cpus'] = ApiClient.convertToType(data['cpus'], 'Number');
            }
            if (data.hasOwnProperty('memory')) {
                obj['memory'] = ApiClient.convertToType(data['memory'], 'Number');
            }
            if (data.hasOwnProperty('orchestration_stack_id')) {
                obj['orchestration_stack_id'] = ApiClient.convertToType(data['orchestration_stack_id'], 'String');
            }
            if (data.hasOwnProperty('flavor_id')) {
                obj['flavor_id'] = ApiClient.convertToType(data['flavor_id'], 'String');
            }
            if (data.hasOwnProperty('taggings')) {
                obj['taggings'] = ApiClient.convertToType(data['taggings'], [Tagging]);
            }
            if (data.hasOwnProperty('archived_at')) {
                obj['archived_at'] = ApiClient.convertToType(data['archived_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Vm.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Vm.prototype['name'] = undefined;

/**
 * Description of the Vm
 * @member {String} description
 */
Vm.prototype['description'] = undefined;

/**
 * @member {Date} source_created_at
 */
Vm.prototype['source_created_at'] = undefined;

/**
 * @member {Date} source_deleted_at
 */
Vm.prototype['source_deleted_at'] = undefined;

/**
 * @member {String} source_id
 */
Vm.prototype['source_id'] = undefined;

/**
 * @member {String} source_ref
 */
Vm.prototype['source_ref'] = undefined;

/**
 * @member {String} tenant_id
 */
Vm.prototype['tenant_id'] = undefined;

/**
 * Cross-Source Unique Reference
 * @member {String} uid_ems
 */
Vm.prototype['uid_ems'] = undefined;

/**
 * @member {String} hostname
 */
Vm.prototype['hostname'] = undefined;

/**
 * @member {String} power_state
 */
Vm.prototype['power_state'] = undefined;

/**
 * Total number of CPUs
 * @member {Number} cpus
 */
Vm.prototype['cpus'] = undefined;

/**
 * Total RAM in bytes
 * @member {Number} memory
 */
Vm.prototype['memory'] = undefined;

/**
 * @member {String} orchestration_stack_id
 */
Vm.prototype['orchestration_stack_id'] = undefined;

/**
 * @member {String} flavor_id
 */
Vm.prototype['flavor_id'] = undefined;

/**
 * @member {Array.<module:model/Tagging>} taggings
 */
Vm.prototype['taggings'] = undefined;

/**
 * @member {Date} archived_at
 */
Vm.prototype['archived_at'] = undefined;






export default Vm;

