/**
 * Topological Inventory
 * Topological Inventory
 *
 * OpenAPI spec version: 0.1.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VolumeType model module.
 * @module model/VolumeType
 * @version 0.1.0
 */
class VolumeType {
    /**
     * Constructs a new <code>VolumeType</code>.
     * @alias module:model/VolumeType
     */
    constructor() { 
        
        VolumeType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VolumeType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VolumeType} obj Optional instance to populate.
     * @return {module:model/VolumeType} The populated <code>VolumeType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VolumeType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], Object);
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], Object);
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], Object);
            }
            if (data.hasOwnProperty('source_ref')) {
                obj['source_ref'] = ApiClient.convertToType(data['source_ref'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('archived_at')) {
                obj['archived_at'] = ApiClient.convertToType(data['archived_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} id
 */
VolumeType.prototype['id'] = undefined;

/**
 * @member {Object} tenant_id
 */
VolumeType.prototype['tenant_id'] = undefined;

/**
 * @member {Object} source_id
 */
VolumeType.prototype['source_id'] = undefined;

/**
 * @member {String} source_ref
 */
VolumeType.prototype['source_ref'] = undefined;

/**
 * @member {String} name
 */
VolumeType.prototype['name'] = undefined;

/**
 * @member {String} description
 */
VolumeType.prototype['description'] = undefined;

/**
 * @member {Date} archived_at
 */
VolumeType.prototype['archived_at'] = undefined;






export default VolumeType;

